tweag/inline-java

- jvm/benchmarks/Main.hs
- jvm/jvm.cabal
- shell.nix
> Add micro benchmarks to jvm package.

- jvm/src/Language/Java.hs
> Cache class and method ID lookups.

- src/Language/Java/Inline.hs
This patch drops the use of reflect/reify to workaround
https://ghc.haskell.org/trac/ghc/ticket/12778. Now we only
coerce/uncoerce. This means that e.g. `[java| $rdd.map($f) |]` works
as expected, whereas before Reflect/Reify instances were required for
the `RDD` type.
> Better workaround for GHC addModFinalizer bug.

- inline-java.cabal
- jvm-streaming/jvm-streaming.cabal
- jvm/jvm.cabal
- stack-HEAD.yaml
- stack.yaml
No need to extra-libraries pthread anymore.
> Use latest released thread-local-storage.

- jvm/src/Language/Java.hs
> Delete local references and cache more class lookups.

- inline-java.cabal
- src/Language/Java/Inline.hs
- tests/Language/Java/InlineSpec.hs
Addresses https://github.com/tweag/inline-java/issues/48
> Implement import statements.

- src/Language/Java/Inline.hs
These do not always correspond. The system class loader is immutable,
whereas the calling context might want to set their own class loader.
This is the case e.g. of Spark.
Fixes tweag/sparkle#108.
> Use the context class loader, not the system class loader.

- jni/src/Foreign/JNI/String.hs
There are two issues addressed by this patch.
The first problem is that `fromChars`, yielded a bytestring which didn't include the terminating `NUL` character. The bytestring, however, pointed to a C string that was `NUL` terminated, and this
made the representation to work most of the time.
`toByteString`, in addition, was not discarding the terminating `NUL` character, thus
```Haskell
toByteString (fromChars a) `BS.append` ";"
```
would contain a `NUL` character before ";" when `fromChars` is fixed.
The second problem is that formerly the memory used by JNI strings created with `fromChars` lived in the C heap, putting no pressure on the Haskell GC to collect them. Now they live in the Haskell heap.
> Fix NUL handling in JNI strings.

- jni/src/Foreign/JNI.cpphs
- jni/src/Foreign/JNI/Types.hs
- jvm-streaming/src/Language/Java/Streaming.hs
- jvm/jvm.cabal
- jvm/src/Language/Java.hs
- jvm/tests/Language/JavaSpec.hs
* Removes Uncurry
* Removes second argument of Reflect and Reify
* Removes Reify and Reflect for J values.
I will submit a PR updating sparkle later.
> Simplify reify and reflect classes

- src/Language/Java/Inline/Plugin.hs
Has "ghc test.hs" work without further parameters.
> Include contents of bctable.h in stubs.

- jni/CHANGELOG.md
- jni/src/Foreign/JNI.hs
- jvm/src/Language/Java.hs
Adds withLocalRef and adjusts newLocalRef.
These changes are needed to make a PR of https://github.com/tweag/sparkle/compare/fd/dataset
> withLocalRef

- BUILD
- WORKSPACE
- jni/BUILD
This includes the whole cc build removal.
> Update bazel files to latest rules_haskell.

- WORKSPACE
- jvm-batching/src/main/haskell/Language/Java/Batching.hs
- jvm/src/Language/Java.hs
- src/Language/Java/Inline/Magic.hsc
The code is now forward compatible with future breaking changes.
> Turn on more warnings

- jvm/src/common/Language/Java/Internal.hs
- jvm/src/common/Language/Java/Unsafe.hs
- src/common/Language/Java/Inline/Internal.hs
This implementation should be equivalent to #135, but it only needs one additional type class and three instances of it.
> Introduce another implementation of Variadic

- .buildkite/pipeline.yml
- .circleci/config.yml
- .gitmodules
- README.md
- jvm/src/linear-types/Language/Java/Safe.hs
- nixpkgs.nix
- shell-linear-types.nix
- shell-stack-linear-types.nix
- shell.nix
- src/linear-types/Language/Java/Inline/Safe.hs
- stack-linear.yaml
> Make new, call and callStatic variadic in the safe interface

- examples/directory-server/LICENSE
- examples/directory-server/README.md
- examples/directory-server/directory-server.cabal
- examples/directory-server/src/Directory/Server.hs
- examples/directory-server/src/Directory/Server/Http.hs
- examples/directory-server/src/Directory/Server/Monad.hs
- examples/directory-server/src/Directory/Server/Monad/Classes.hs
- examples/directory-server/src/server.hs
- shell-stack-linear-types.nix
- stack-linear.yaml
See examples/directory-server/README.md.
> An http server using the safe interfaces to inline-java

- benchmarks/wizzardo-http/Setup.hs
- benchmarks/wizzardo-http/build.gradle
- benchmarks/wizzardo-http/settings.gradle
- benchmarks/wizzardo-http/src/DbHandler.hs
- benchmarks/wizzardo-http/src/Language/Java/Function.hs
- benchmarks/wizzardo-http/src/Main.hs
- benchmarks/wizzardo-http/src/Wizzardo/Http/Handler.hs
- benchmarks/wizzardo-http/wizzardo-http-benchmark.cabal
- env-linear.sh
- jni/src/linear-types/Foreign/JNI/Safe.hs
- set-java-home.sh
- stack-linear.yaml
Implements the plaintext and json benchmarks of https://www.techempower.com/benchmarks using wizzardo-http.
The benchmark scaffolding is implemented in:
https://github.com/facundominguez/FrameworkBenchmarks/compare/master...facundominguez:fd/wizzardo-http-inline-java
> Add a benchmark using wizzardo-http

- jvm-batching/CHANGELOG.md
- jvm-batching/README.md
- jvm-batching/src/main/haskell/Language/Java/Batching.hs
- jvm-batching/src/main/java/io/tweag/jvm/batching/BatchWriters.java
- jvm-batching/src/test/haskell/Language/Java/BatchingSpec.hs
- jvm-streaming/src/main/haskell/Language/Java/Streaming.hs
- jvm/CHANGELOG.md
- jvm/src/common/Language/Java/Unsafe.hs
This is the reify half of https://github.com/tweag/inline-java/issues/112.
> Handle null values when reifying batches

- jni/jni.cabal
- jni/src/common/Foreign/JNI/Internal/BackgroundWorker.hs
- jni/src/common/Foreign/JNI/Internal/RWLock.hs
- jni/src/common/Foreign/JNI/Unsafe.hs
- jvm/benchmarks/Main.hs
- jvm/src/common/Language/Java/Unsafe.hs
... and does some other refactorings. See the individual commits.
> Remove runInAttachedTread from reifyMVector (closes #152)

- jvm-batching/README.md
- jvm-batching/build.gradle
- jvm-batching/src/main/java/io/tweag/jvm/batching/BatchReader.java
- jvm-batching/src/main/java/io/tweag/jvm/batching/BatchWriter.java
> Create artifacts for publication in Maven Central

- jni/src/common/Foreign/JNI/Unsafe.hs
- jvm-batching/src/test/haskell/BUILD.bazel
- jvm-batching/src/test/haskell/Main.hs
- jvm-streaming/src/test/haskell/BUILD.bazel
- jvm-streaming/src/test/haskell/MainBazel.hs
> Run tests in jvm-batching and jvm-streaming with bazel

- jvm/src/linear-types/Language/Java/Safe.hs
This PR adds the `fromArray` function to the safe interface of `jvm`. `fromArray` essentially serves as an inverse to `toArray`, that is, it converts a reference to a Java array to a Haskell list of Java references. It will be used in `sparkle` to implement `collectJ` and similar, in which we need a way to extract a list of references from a Java array without using the `Reify` instance.
> Add fromArray
