- inline-java.cabal
- src/Language/Java/Inline.hs
- tests/Language/Java/InlineSpec.hs
Whenever a class definition has inline anonymous classes, companion
.class files are generated. So we need to embed those in binaries and
load them too. Function literals are syntactic sugar for anonymous
classes.
> Support compiling source units (.java files) that generate multiple .class files.

- inline-java.cabal
- src/Language/Java/Inline/Cabal.hs
It's not possible to build inline-java code if it has external JVM
dependencies, such as third party packages downloaded from Maven
Central. We need to tell `javac` where to find these dependencies, by
setting the CLASSPATH. These can get quite long, and tiresome to set
by hand, so we Cabal hooks to extract them from external build tool
configurations.
For now only support Gradle. We'll probably want Maven support later.
> Utility code to extract the CLASSPATH from Gradle build configuration.

- jvm/src/Language/Java.hs
The problem with the existing instance, say `Reflect [Text] ('Array ('Class "java.lang.String"))` is that it always allocates an `Object[]`, while the upper layers need/expect a `java.lang.String[]`.
There are two things I'm not convinced about in this patch:
1. It doesn't work for generics. Generics have `IsReferenceType` instance with a constraint:
```Haskell
instance IsReferenceType ty => IsReferenceType ('Generic ty tys)
```
AFAIU all generics are reference types. What's the point of asking for the extra constraint to use functions like `referenceTypeName`?.
2. It looks like `Reflect` and `Reify` should have `IsReferenceType` as a superclass constraint. It isn't possible to define them for primitive types, or at least the `J ('Prim symbol)` appearing in the signature of …
> Fix Reflect instance for lists so it uses the right class to create a java array.

- jni/jni.cabal
- jni/src/Foreign/JNI.hs
- jni/src/Foreign/JNI/NativeMethod.hsc
- jni/src/Foreign/JNI/Types.hs
This provides an alternate method of binding C/Haskell code to Java
classes. Binding can happen at runtime, on-the-fly, rather than at
program initialization time.
> Bind the JNINativeMethod data structure and RegisterNatives().

- jvm-streaming/LICENSE
- jvm-streaming/README.md
- jvm-streaming/jvm-streaming.cabal
- jvm-streaming/src/Language/Java/Streaming.hs
- jvm-streaming/tests/Language/Java/StreamingSpec.hs
- jvm-streaming/tests/Main.hs
- jvm-streaming/tests/Spec.hs
- stack.yaml
The `jvm-streaming` package provides Reflect/Reify instances for Java
iterators (i.e. anything that implements interface
`java.util.Iterator`). It's a separate package, rather than being
included in `jvm`, because (a) we don't want `jvm` to choose between
`streaming`, `pipes`, `conduit` etc, (b) it enables us to depend on
inline-java without introducing circular dependencies.
Depending on inline-java allows us to expose a Haskell `Stream` as
a Java iterator of anonymous class, the way iterators are usually
implemented.
This PR obsoletes most of tweag/sparkle#77. Differences:
* Maps iterators to `Stream` from the `streaming` package, instead of
defining an ad hoc Haskell iterator type.
* Does not require sparkle. Since iterators are part of the Java
standard library, we should bind them …
> Support streaming from Java iterators.

- .gitmodules
- jni/jni.cabal
- stack.yaml
No need to have a vendored submodule anymore.
> Switch to latest inline-c release.

- jni/src/Foreign/JNI/Types.hs
- jvm/benchmarks/Main.hs
- jvm/jvm.cabal
- src/Language/Java/Inline.hs
The singleton instance used JNI.String, which is a wrapper over ByteStrings, relies on unsafePerformIO and related functions to do comparisons. For some reason, these calls are not always floated to the top-level, which means that they are redone everytime a comparison needs to be performed.
Redoing comparisons hurts performance of call and callStatic in the jvm package.
When using Prelude.String instead, the comparisons become pure, which allows their results to be floated and cached when call and callStatic are evaluated multiple times at the same types.
> Use Prelude.String's in the Sing (t :: JType) instance.

- jni/src/Foreign/JNI.cpphs
This wrapper around Java/Scala/Any-JVM-language exceptions was not
previously exposed, making it pretty hard to handle it.
> Expose JVMException.

- src/Language/Java/Inline.hs
- tests/Language/Java/InlineSpec.hs
These are made transparent to inline-java by unfolding any type
synonyn at the head of the type.
> Support type synonyms in variable antiquotation.

- jni/jni.cabal
- jni/src/Foreign/JNI.cpphs
- jni/src/Foreign/JNI/Internal.hs
- jni/src/Foreign/JNI/NativeMethod.hsc
- jni/src/Foreign/JNI/Types.hs
- jvm/src/Language/Java.hs
- src/Language/Java/Inline.hs
678d5b1416df435f84fe31ff1110eb15480f96c6 showed how it is all too easy
to pass an ill-formed class name to findClass. We do get a runtime
error in this case but sometimes the error returned by the JVM is
confusing. Better to statically rule out the possibility of
a well-formation issue to begin with. That's what the abstract newtype
wrappers introduced here seek to achieve: extra safety and piece of
mind.
Note that this patch doesn't actually validate much (can always add
more validations in the future), but it at least enforces a style
where only Java surface syntax "dotty" names are used uniformly, so
you should now never need to worry about JNI style "slashy" names.
This is a backward compatibility breaking change.
cc @robinbb @edsko @alpmestan
> Make the result of JNI.String constructors bear the proof of well-formation.

- jni/src/Foreign/JNI.cpphs
In GHCi, we don't want 'withJVM'. We want to initialize the JVM once,
at the beginning, and then keep it in scope until GHCi exits.
> Add newJVM/destroyJVM. Useful for GHCi.

- jvm/src/Language/Java.hs
- jvm/tests/Language/JavaSpec.hs
- src/Language/Java/Inline.hs
The original rationale for passing in a singleton was that like `call` and
other functions, it becomes possible to `SPECIALIZE` `callStatic` to
certain classes. But this isn't terribly useful, indeed entirely redundant
with what could be achieved with simple inlinining, hence making the added
syntactic overhead unjustifiable.
```
callStatic (sing :: Sing "some.java.Class") ...
```
is now
```
callStatic "some.java.Class" ...
```
This is a breaking change. Best to change this now before this really
becomes enshrined.
cc @alpmestan :)
> Pass class name as a JNI.String to callStatic, not as a singleton.

- jvm/src/Language/Java.hs
- jvm/tests/Language/JavaSpec.hs
This should make it easier to make bindings to enums. Example:
```haskell
monday :: IO (J ('Class "java.time.DayOfWeek"))
monday = getStaticField "java.time.DayOfWeek" "MONDAY"
```
> Add getStaticField

- src/Language/Java/Inline.hs
- stack.yaml
- tests/Language/Java/InlineSpec.hs
Fixes #37
Doesn't work for all cases, such as if you have some strange phantom type:
```haskell
type JComponent a = J ('Class "java.awt.Component")
```
> unliftJType for 0-arg type synonyms

- jni/jni.cabal
- jni/src/Foreign/JNI/Types.hs
- jvm/jvm.cabal
- jvm/src/Language/Java.hs
- jvm/tests/Language/JavaSpec.hs
* Implement instance Show (Sing (a :: JType)).
* Construct IsReferenceType instances from Sing values.
> Extend newArray to work over any reference type. (#24)

- jvm/jvm.cabal
- jvm/src/Language/Java.hs
This is useful for using inline-java in sparkle. Instance needs to be
defined in jvm package to avoid orphan instances.
> Make Choice Coercible to a Java boolean.

- src/Language/Java/Inline.hs
Whereas before, inline-java could only unlift bare type abbreviations with
no parameters, we now support any type synonym, provided it is fully
applied at the call site.
Depends on #53.
> Support unfolding type synonyms that have parameters.

- jvm/src/Language/Java.hs
In #44, we removed singletons from the signature of `callStatic`. This
change aligns `classOf` to this new world order, so that e.g.
```haskell
callStatic (classOf foo) "method" [arg1, ...]
```
is well-typed.
This, like #44, is a BC breaking change.
> Don't return a singleton in classOf.

- src/Language/Java/Inline.hs
- tests/Language/Java/InlineSpec.hs
This makes it possible to have antiquotation variables with generic
parameters. The parameters must still be ground, since inline-java
needs to know at compile time the full types of all variables.
> Support for unlifting Java generics.

- jvm/benchmarks/Main.hs
- src/Language/Java/Inline.hs
- tests/Language/Java/InlineSpec.hs
Otherwise jdk 1.7 complains when antiquotations are used in inner classes.
> Make antiquoted variables final

- jvm/jvm.cabal
- jvm/src/Language/Java.hs
- jvm/src/Language/Java/TH.hs
See the various commit messages in this series for details. This PR
adds:
* A new function `jobject`, which extracts a `J ty` from anything that
is coercible, provided `ty` is a reference type.
* defaults for `Reify` and `Reflect` when a `Coercible` instance
already exists.
* A new TH macro, `makeConversions`, designed to make it much less
verbose to define a newtype wrapper. The desugaring of this macro is
easy to understand, so its use is entirely optional.
This series aims to resolve tweag/sparkle#93.
> Better handling of newtype wrappers.

- jni/jni.cabal
- jni/src/Foreign/JNI/Types.hs
- jvm/benchmarks/Main.hs
- jvm/jvm.cabal
In partial fulfillment of #65, this PR adds code to quantify the cost
of creating new references to JVM objects. For comparison, we also
include microbenchmarks for creating foreign pointers directly, in two
different ways.
Includes a refactoring of benchmarks harness to make it possible to
run them independently.
> Add new micro benchmarks to quantify cost of references.

- jvm/jvm.cabal
- jvm/src/Language/Java.hs
JNI Local references don't disappear until the control flow escapes
the current native call frame. This can be a very long time indeed, or
in fact never in the case of standalone apps. So we introduce `push`
to allocate a new block to store local references in. These references
can be discarded all at once when the control flow exits the scope of
the push. There is only one way to return a value out of the scope of
a push: by calling one of `popWithValue` or `popWithObject`. The
latter function is expected to be the common case. It's a thin wrapper
on top of `PopLocalFrame()` in the JNI, which only works for returning
objects.
There is nothing preventing the return of a local reference outside of
the scope in which it was allocated. But neither do any alternatives
that don't in one way or …
> Implement push and pop family of functions for managing local references.

- inline-java.cabal
- src/Language/Java/Inline.hs
- src/Language/Java/Inline/Magic.hs
The static pointer table (SPT) in GHC currently lacks any typing
information. So to discriminate between static pointers that refer to
inline-java bytecode vs other random static pointers, we used
ghc-heap-view as a workaround.
It was a gross hack. It worked. But the cost of using this hammer is
that profiling builds were impossible.
This commit instead uses a much smaller hammer. Where ghc-heap-view
requires very intimate knowledge of much of GHC's memory layout, we
only use 'unpackClosure#'. Because we don't have the full power of
ghc-heap-view, we can't inspect the info table provided to us by this
primitive. But what we can do is inspect the environment of the
closure. If we find a pair of magic integers in there, then we assume
the static pointer does point to Java bytecode.
> Do away with ghc-heap-view dependency.

- jni/src/Foreign/JNI.cpphs
A writer could wait indefinitely if there were readers running at the time it requested the lock.
> Fix random lockups in the RW locks to finalize JNI.

- src/Language/Java/Inline/Plugin.hs
- tests/Language/Java/InlineSpec.hs
Addresses issue (1) mentioned in https://github.com/tweag/inline-java/issues/89.
> Allow inline-java to marshal inner class references.

- CHANGELOG.md
- jni/jni.cabal
- jni/src/Foreign/JNI.cpphs
- stack-8.2.yaml
This way we can make the application responsible for detaching the threads that have been attached.
Tracing & analysis in jni would require this to trace when threads are attached and detached from the JVM.
> Don't attach threads automatically

- CHANGELOG.md
- jni/src/Foreign/JNI.cpphs
I may have reviewed #86 too quickly before the merge. Looking at it
more closely, I don't understand why the current code actually works.
In particular, because jniEnv is not set during `newJVM`. This version
spells out the key invariant explicitly. All other functions maintain
this invariant, so `getJNIEnv` can be simpler.
> Rewrite environment checking

- jvm/src/Language/Java.hs
Fixes a `java.io.NotSerializableException` when trying to convert back a java value to the `()` type
> Allows to convert `()` from java

- jvm-streaming/src/Language/Java/Streaming.hs
- jvm/src/Language/Java.hs
- src/Language/Java/Inline/Magic.hsc
- src/Language/Java/Inline/Plugin.hs
With the changes in this PR, it is now possible to:
```haskell
newtype T = T (J ('Class ...))
deriving (Coercible, Interpretation, Reify, Reflect)
```
This is important, because what we're also doing in this PR is
dropping all invariants about how newtype wrapped stuff should *not*
be reifiable/reflectable. This means we'll want most newtype wrapped
references to be reifiable/reflectable. That's only really viable if
we can keep the boilerplate to a minimum, in particular be making
these instances derivable.
> Make Coercible/Reify/Reflect derivable.

- jvm/CHANGELOG.md
- jvm/src/Language/Java.hs
`Vector Double` reflects to/reifies from `double[]`
I had to add these in order to implement `randomSplit` which takes `double[]` as an argument (not `Double[]`): https://github.com/MailOnline/sparkle/blob/9c3788a28bfcc8d6c9ed4a87b329aea2f48ff57f/src/Control/Distributed/Spark/RDD.hs#L230
I'd be interested to know if there's a better way to achieve this ^
> Add Reflect/Reify for Vector Double

- jni/src/Foreign/JNI.hs
This avoids requiring that the build system knows about cpphs.
> Replace .cpphs suffix with -pgmP directive.

- jni/src/Foreign/JNI.hs
This is what JNI expects. Without this we get errors during build
though these do seem non-fatal. This cast is already performed just
few lines down.
```
2017-12-29 16:53:45.011881: [info] /nix/store/bw5qbjqf3mqis99kyzz973q4djdxv9ba-ghc-8.0.2/bin/ghc -c -fPIC -odir .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build -I.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/autogen -I.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build -I/nix/store/347h96g34wg35l2kv8fbn73i4m40gzdc-openjdk-8u152b16/include -I/nix/store/44dk7fyy724x2vlm4xvcm8l2wcm0l7iy-git-2.15.1/include -I/nix/store/fj4shhg1mkpqlh7py00zfccvw9yh6snh-gradle-4.4/include -optc-O2 '-optc-std=c11' -hide-all-packages -no-user-package-db -package-db /home/shana/.stack/snapshots/x86_64-linux-nix/lts-9.18/8.0.2/pkgdb -package-db …
```
> Cast jniEnv ref to void**

- .gitignore
- BUILD
- WORKSPACE
- jni/BUILD
- jvm-streaming/BUILD
- jvm/BUILD
- nixpkgs.nix
- src/Language/Java/Inline/Magic.hsc
This is a collection of build files that work with the given WORKSPACE
file. This should allow the user to run `bazel test //...` which will
build run all tests in `inline-java`: as of time of writing, this is
spec tests in `inline-java` and `jvm-streaming`.
* We're repeating ourselves a lot w.r.t. prebuilt dependencies. We
need to have all the packages available to GHC at WORKSPACE level
then we also need to know them at BUILD level. We can't just define
them in WORKSPACE and refer to them from BUILD as WORKSPACE only
works in current project: if user wants to use inline-java from
another project, the WORKSPACE file here is irrelevant: indeed
they'll have to define all these things in their own WORKSPACE.
-----------------------------
Old PR description below. Note that nearly all points …
> Bazel build files for inline-java

- src/Language/Java/Inline/Plugin.hs
Fixes #101.
------------
This is necessary for things like bazel where the file at build time might actually live in something like `external/inline_java/cbits/bctable.h` if inline-java is being built as a dependency rather than directly as is the case with `sparkle` for example.
> Look for cbits/bctable.h instead of assuming the build directory.

- README.md
This PR replaces the Tweag's logo in `README.md` by its current version.
> Update Tweag's logo in README.md

- src/Language/Java/Inline/Cabal.hs
Newer versions of Gradle think it's a great idea to output a summary
of the release notes even when the `-q` flag for "quiet!" is passed,
but only on the first run. This trashes the output that we're
capturing to get at the CLASSPATH. So as a workaround, we make sure to
only capture the *last* line of output from `gradle build -q`.
> Workaround Gradle sometimes trashing output in recent versions.

- jni/src/Foreign/JNI/Types.hs
My environment is cabal-install-2.4.1.0, ghc-8.6.4, Arch Linux. (without stack)
The package singletons-2.5.*, which is the only available versions for base-4.12, doesn't define `showsSingPrec`.
A new `#if` branch is added to avoid using `showsSingPrec` to prevent compilation failure.
In addition, the
instance Show (Sing (a :: [JType]))
is excluded as well because `Data.Singletons.ShowSing` now defines the
instance (ShowSing a, ShowSing [a]) => Show (Sing z),
which leads to an ambiguous instance error.
I didn't added an entry to `CHANGELOG.md` because I couldn't figure out where to put a `jni`-specific one.
> Avoid using showsSingPrec when building against singletons>=2.5

- jvm/src/Language/Java.hs
This is necessary in order to give a Haskell thread the ability to use class loaders that aren't available to JNI.findClass.
Related to https://github.com/tweag/sparkle/issues/72.
> Allow to set the call to use to find classes.

- jvm/jvm.cabal
We were previously only compatible with 8.0.2, not 8.0.1 due to an
upstream bug. To avoid CPP, we just drop the 8.x series, which by this
point is old anyways.
> Require GHC 8.2 minimum

- jni/src/linear-types/Control/Monad/Lift/Linear.hs
- jni/src/linear-types/Foreign/JNI/Safe.hs
- jni/src/linear-types/System/IO/Linear/Extras.hs
- jvm/src/linear-types/Language/Java/Safe.hs
- src/common/Language/Java/Inline/Internal/QQMarker.hs
- src/common/Language/Java/Inline/Plugin.hs
- src/linear-types/Language/Java/Inline/Internal/QQMarker/Safe.hs
- src/linear-types/Language/Java/Inline/Safe.hs
- stack-linear.yaml
The linear interfaces were using `Linear.IO`, that might not be particularly easy to integrate in applications which use other monads.
I propose here a class to lift non-linear monads into linear monads. jni uses this to offer operations that run on any linear monad that can lift the non-linear `IO`.
```haskell
class (Linear.Monad m, NonLinear.Monad (LiftedM m)) => MonadLift m where
type LiftedM m :: * -> *
lift :: LiftedM m a -> m a
liftU :: LiftedM m a -> m (Unrestricted a)
```
Thus, an application can provide an instance of `Linear.Monad` for any wrapper of a regularly looking monadic stack. e.g.
```haskell
data App a = App (ReaderT Env IO a)
deriving (Monad, Functor, Applicative, MonadIO)
data LinearApp a = LinearApp (App a)
instance Linear.Monad LinearApp where
...
instance …
```
> Use an abstract monad in the linear interfaces

- .buildkite/pipeline.yml
- .circleci/config.yml
- shell-stack.nix
- shell.nix
- stack.yaml
Getting the cache key to be adequately conservative in CircleCI is a
nightmare. And even with caching, reinstalling all dependencies +
restorting the cache takes so much time that an identity build takes 10
minutes or more. The solution is to use BuildKite, like rules_haskell
and rules_sh already do. This won't work (yet) for macOS. But for the
Linux jobs this should speed things up quite significantly, while also
making the CI job definitions simpler.
> Move Stack and Bazel linux jobs to buildkite

- benchmarks/micro/Main.hs
- jvm-batching/src/main/haskell/Language/Java/Batching.hs
- jvm/BUILD.bazel
- jvm/CHANGELOG.md
- jvm/benchmarks/Main.hs
- jvm/jvm.cabal
- jvm/src/common/Language/Java/Internal.hs
- jvm/src/common/Language/Java/Unsafe.hs
- jvm/src/linear-types/Language/Java/Safe.hs
- jvm/tests/Language/JavaSpec.hs
- src/common/Language/Java/Inline/Internal.hs
- src/common/Language/Java/Inline/Unsafe.hs
- src/linear-types/Language/Java/Inline/Safe.hs
**This PR is mutually exclusive with #133.**
`call` previously took a list of `JValue`'s. Using the dictionaries
embedded in each element, it could construct a `MethodID`. However, this
`MethodID` was not cached as well as one would hope, say when multiple
calls are made to the same method at the same argument types but
different values. Another problem was that all arguments to the method
had to be packed into a list and coerced into a `JValue` before being
passed to the method. This was syntactic overhead. The solution is to
make `call`, `new` and `callStatic` variadic, using the same GADT
solution as for variadic `printf`.
We now pass an extra spec argument to `call`. Like the format string in
`printf`, this argument determines how many more arguments need to be
passed to `call`. …
> jvm: make call* variadic in the unsafe interface

- jvm-streaming/src/main/haskell/Language/Java/Streaming.hs
- jvm-streaming/src/test/haskell/Language/Java/StreamingSpec.hs
Turns out that fixing one of the tests in jvm-streaming uncovered a bug I suspected we had for quite a while.
registerNatives affects all objects of an inner class, and we were calling it with different functions assuming that it only would affect the newly created instance.
This is a short term fix. We should aim for something better as discussed in the code.
>  Fix interdependence bug between reflected streams

- .buildkite/pipeline.yml
- benchmarks/wizzardo-http/src/main/haskell/DbHandler.hs
- benchmarks/wizzardo-http/src/main/haskell/Language/Java/Function.hs
- benchmarks/wizzardo-http/src/main/haskell/Main.hs
- benchmarks/wizzardo-http/src/main/haskell/Wizzardo/Http/Handler.hs
- examples/directory-server/src/Directory/Server.hs
- examples/directory-server/src/Directory/Server/Http.hs
- jni/src/linear-types/Foreign/JNI/Safe.hs
- jni/src/linear-types/Foreign/JNI/Types/Safe.hs
- jvm/src/linear-types/Language/Java/Safe.hs
At a suggestion of @hanshoglund, I'm forbidding safe quasiquotations from manipulating unrestricted references of type `Unrestricted (J ty)`. Instead, the user must use the isomorphic type `UnsafeUnrestrictedReference (J ty)`.
This is more verbose, but it is very explicit in that the programmer forgoes the correctness guarantees of the safe interface for those references.
> Use UnsafeUnrestrictedReference to mark unrestricted references in the safe interface

- WORKSPACE
- jni/BUILD.bazel
- jni/jni.cabal
- jni/src/common/Foreign/JNI/Internal/BackgroundWorker.hs
This is a preliminary implementation of an upper bound
on the number of tasks that can be left pending for a
BackgroundWorker to execute.
This strategy is based on busy-waiting, which should be avoided.
> change: bound the queue of background workers (closes #154)

- .buildkite/pipeline.yml
- jni/src/common/Foreign/JNI/Internal.hs
- jni/src/common/Foreign/JNI/Unsafe.hs
- jni/tests/Foreign/JNISpec.hs
We wrap getMethodID and getStaticMethodID from Foreign.JNI.Unsafe.Internal into a function
that produces a more verbose and more helpful exception when it fails.
Solves #148
> add: verbose Exception on getMethodID failure

- jni/CHANGELOG.md
- jni/src/common/Foreign/JNI/Unsafe/Internal.hs
- jni/src/common/Foreign/JNI/Unsafe/Internal/Introspection.hs
- jni/tests/Foreign/JNISpec.hs
Solves #166 
This PR adds a function `showException :: JVMException -> IO Text` which provides the stack trace of the underlying `JThrowable`.
This function may be used in a custom `instance Show JVMException` instead of the default one. Once `JVMException` has a proper `Show` instance, we will be able to remove the call to `ExceptionDescribe` in `Foreign.JNI.Unsafe.Internal.throwIfException`, which is the goal of #166
> wip: print Throwable stack traces

- src/common/Language/Java/Inline/Internal.hs
- src/common/Language/Java/Inline/Internal/Magic.hsc
Instead of leaking one reference per class loaded by `defineClass`,
We gather them in a Java array stored in a global ref.
Solves #156
> change: gather class references in loadJavaWrappers

- jvm/src/linear-types/Language/Java/Safe.hs
I wrapped all the `Interpretation`, `Reify`, and `Reflect` instances in a call to `withStatic`, as in the unsafe version to derive `Static` instances for these instance declarations.
> Added withStatic in safe version to derive Static instances

- jni/src/linear-types/Foreign/JNI/Safe.hs
- tests/Language/Java/Inline/SafeSpec.hs
I made the type signatures of the two above-mentioned functions more general, by allowing any type coercible to a `J ty` to be copied or deleted, as is the case in the unsafe version. Note that in most cases, one will now need to import `Foreign.JNI.Types` and `Foreign.JNI.Types.Safe` in order to use these functions, so that the compiler can derive the appropriate `Coercible` instances.
> Made safe deleteLocalRef and newLocalRef use Coercible for more generality

- jvm/src/linear-types/Language/Java/Safe.hs
This commit fixes the bug where the safe `call` didn't delete the calling object despite linear multiplicity. Also, it fixes the bug with the return type singleton passed to `callToValue`.
> Two bug fixes in `call`
